spring.application.name=sarthi-backend

server.servlet.context-path=/sarthi-backend


#spring.datasource.url=jdbc:mysql://localhost:3306/sarthidb?useSSL=false&serverTimezone=GMT&useLagacyDatetimeCode=false
#spring.datasource.username=root
#spring.datasource.password=root


spring.datasource.url=${DATABASE_UAT_URL}
spring.datasource.username=${DATABASE_UAT_USERNAME}
spring.datasource.password=${DATABASE_UAT_PASSWORD}


# spring.datasource.url=jdbc:mysql://sarthi-mysql-prod.mysql.database.azure.com:3306/sarthidb?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
# spring.datasource.username=DkgSarthi
# spring.datasource.password=Test@123


# spring.datasource.url=jdbc:mysql://sarthi-mysql-prod.mysql.database.azure.com:3306/sarthidb?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
# spring.datasource.username=DkgSarthi
# spring.datasource.password=Test@123




spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

 #spring.datasource.url=jdbc:mysql://sarthi-mysql-prod.mysql.database.azure.com:3306/sarthidb?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
 #spring.datasource.username=DkgSarthi
 #spring.datasource.password=Test@123








#  spring.datasource.url=jdbc:mysql://sarthi-mysql-prod.mysql.database.azure.com:3306/sarthidb?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
#  spring.datasource.username=DkgSarthi
# spring.datasource.password=Test@123

# spring.datasource.url=jdbc:mysql://localhost:3306/rites_erc_inspection
# spring.datasource.username=root
# spring.datasource.password=

# Hikari Connection Pool
#spring.datasource.hikari.minimum-idle=20
#spring.datasource.hikari.maximum-pool-size=100
#spring.datasource.hikari.idle-timeout=300000
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.pool-name=HikariPool
#spring.datasource.hikari.leak-detection-threshold=60000

#cris.base-url=https://trial.ireps.gov.in/immsapi
cris.base-url=https://ireps.gov.in/immsapi
cris.username=${CRIS_USERNAME}
#cris.password=password
cris.password=${CRIS_PASSWORD}

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=none
spring.datasource.initialization-mode=always
spring.jpa.generate-ddl=false
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# DO NOT CHANGE
jwt.secretkey = "ayXsCyBIxrHSwAAYsVmUqbagCI937qC0/tpkL8vyx0q+1VT4YeD60PVIt6yOneoH" 
jwt.token.validity = 86400000

spring.cache.type=simple


spring.jpa.properties.hibernate.format_sql = true


spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

# Azure Storage Configuration
# You must provide the connection string for 'ritesblobstorage' here
#azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}

#azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING:sdfghjk}
#azure.storage.container-name=certificates-prod

azure.storage.connection-string="sdfghjk"
azure.storage.container-name=certificates
azure.storage.images-container-name=ercinspectionimages-uat


management.endpoint.health.show-details=always

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SARTHI_MAIL_USERNAME}
spring.mail.password=${SARTHI_MAIL_UAT_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.mail.properties.mail.debug=true

logging.level.org.springframework.mail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG

# Timeouts
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000


ibs.billing.url=https://ritesinsp.com/IBS2MobileAPI/Sarthi/get-bill-details

