-- V22__create_sleeper_final_ic_tables.sql
-- Create dedicated tables for Sleeper Final IC Edit and Save Changes

CREATE TABLE IF NOT EXISTS `sleeper_final_ic_edit` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ic_number` VARCHAR(100) NOT NULL,
  `certificate_id` BIGINT DEFAULT NULL,
  `book_no` VARCHAR(50) DEFAULT NULL,
  `set_no` VARCHAR(50) DEFAULT NULL,
  `offered_installment_no` VARCHAR(50) DEFAULT NULL,
  `passed_installment_no` VARCHAR(50) DEFAULT NULL,
  `consignee` TEXT DEFAULT NULL,
  `cumm_qty_offered_prev` VARCHAR(50) DEFAULT NULL,
  `qty_prev_passed` VARCHAR(50) DEFAULT NULL,
  `qty_still_due` VARCHAR(50) DEFAULT NULL,
  `ma_number_and_date` TEXT DEFAULT NULL,
  `purchasing_authority` TEXT DEFAULT NULL,
  `description` TEXT DEFAULT NULL,
  `manufacturer` TEXT DEFAULT NULL,
  `tr_rec_date` VARCHAR(50) DEFAULT NULL,
  `no_of_visits` VARCHAR(50) DEFAULT NULL,
  `dates_of_inspection` TEXT DEFAULT NULL,
  `sealing_pattern` TEXT DEFAULT NULL,
  `reasons_for_rejection` TEXT DEFAULT NULL,
  `facsimile_text` TEXT DEFAULT NULL,
  `inspecting_engineer` TEXT DEFAULT NULL,
  `status` VARCHAR(50) DEFAULT NULL,
  `created_by` VARCHAR(100) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(100) DEFAULT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_sleeper_final_ic_edit_ic_no` (`ic_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sleeper_final_ic_save_changes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ic_number` VARCHAR(100) NOT NULL,
  `certificate_id` BIGINT DEFAULT NULL,
  `book_no` VARCHAR(50) DEFAULT NULL,
  `set_no` VARCHAR(50) DEFAULT NULL,
  `offered_installment_no` VARCHAR(50) DEFAULT NULL,
  `passed_installment_no` VARCHAR(50) DEFAULT NULL,
  `consignee` TEXT DEFAULT NULL,
  `cumm_qty_offered_prev` VARCHAR(50) DEFAULT NULL,
  `qty_prev_passed` VARCHAR(50) DEFAULT NULL,
  `qty_still_due` VARCHAR(50) DEFAULT NULL,
  `ma_number_and_date` TEXT DEFAULT NULL,
  `purchasing_authority` TEXT DEFAULT NULL,
  `description` TEXT DEFAULT NULL,
  `manufacturer` TEXT DEFAULT NULL,
  `tr_rec_date` VARCHAR(50) DEFAULT NULL,
  `no_of_visits` VARCHAR(50) DEFAULT NULL,
  `dates_of_inspection` TEXT DEFAULT NULL,
  `sealing_pattern` TEXT DEFAULT NULL,
  `reasons_for_rejection` TEXT DEFAULT NULL,
  `facsimile_text` TEXT DEFAULT NULL,
  `inspecting_engineer` TEXT DEFAULT NULL,
  `status` VARCHAR(50) DEFAULT NULL,
  `created_by` VARCHAR(100) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(100) DEFAULT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_sleeper_final_ic_save_changes_ic_no` (`ic_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
